AWSTemplateFormatVersion: 2010-09-09
Description: Template for EC2 instance
Parameters:
  Subnet:
    Description: The EC2 Instance will be launched in this subnet
    Type: AWS::EC2::Subnet::Id
    Default: subnet-05a75008f0efc4390
  AMIid:
    Description: Image ID
    Type: AWS::EC2::Image::Id
    Default: ami-07ebfd5b3428b6f4d
  Keypair:
    Description: Key pair name
    Type: AWS::EC2::KeyPair::KeyName
    Default: EC2_private
  InstanceType:
    Type: String
    Default: g3s.xlarge

Resources:
  ServerInstance:
    Type: "AWS::EC2::Instance"
    CreationPolicy:
      ResourceSignal:
        Timeout: PT10M
    Metadata:
      Comment: "Deploy Applications to the servers"
      AWS::CloudFormation::Init:
        config:
            files:
                "/etc/cfn/cfn-hup.conf":
                  content: !Sub |
                    [main]
                    stack=${AWS::StackId}
                    region=${AWS::Region}
                    interval=3
                  mode: "000400"
                  owner: "root"
                  group: "root"

                "/etc/cfn/hooks.d/cfn-auto-reloader.conf":
                  content: !Sub |
                    [cfn-auto-reloader-hook]
                    triggers=post.update
                    path=Resources.MyVMInstance.Metadata.AWS::CloudFormation::Init
                    action=/usr/local/bin/cfn-init -v --stack ${AWS::StackName} --resource MyVMInstance --region ${AWS::Region}
                  mode: "000400"
                  owner: "root"
                  group: "root"

    Properties:
      ImageId: !Ref AMIid
      InstanceType: !Ref InstanceType
      KeyName: !Ref Keypair
      SubnetId: !Ref Subnet
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 120
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe

            # Update && upgrade
            apt-get update && apt-get -y upgrade

            ## CFN Initialization ##

            # Install scripts
            apt-get -y install python-pip
            pip install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz

            # Start cfn-init to Install all Metadata content (pacakges, sources, files, commands and services )
            /usr/local/bin/cfn-init -s ${AWS::StackId} -r ServerInstance --region ${AWS::Region} || error_exit 'Failed to run cfn-init'

            # Start cfn-hup daemon so that it will keep listening to any changes to EC2 Instance Metadata.
            /usr/local/bin/cfn-hup || error_exit 'Failed to start cfn-hup'

            # Install packages ##
            apt-get install -y htop docker.io docker-compose git mesa-utils

            # As a last step, signal the stack
            /usr/local/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource ServerInstance --region ${AWS::Region}
